# Generated by Django 4.1.7 on 2023-03-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0007_rename_student_class_name_studentclass_student_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
                ('student_class', models.ManyToManyField(to='student.studentclass')),
            ],
        ),
    ]
