# Generated by Django 4.1.7 on 2023-03-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='attendance',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=20),
        ),
    ]
