# Generated by Django 4.1.7 on 2023-03-14 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_student_class_name_studentclass_student_class_and_more'),
        ('student_attendance', '0002_studentattendance_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='student_class',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.studentclass'),
        ),
    ]
