# Generated by Django 4.1.7 on 2023-03-14 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0003_remove_studentattendance_student_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='name',
        ),
    ]
