# Generated by Django 4.1.7 on 2023-03-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_student_class_name_studentclass_student_class_and_more'),
        ('student_attendance', '0004_remove_studentattendance_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentclass')),
            ],
        ),
    ]
