# Generated by Django 4.1.7 on 2023-03-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0005_attendancedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedetails',
            name='date',
            field=models.DateField(),
        ),
    ]
