# Generated by Django 4.1.7 on 2023-03-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_student_class_name_studentclass_student_class_and_more'),
        ('student_attendance', '0006_alter_attendancedetails_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancedetails',
            old_name='student_class',
            new_name='Class',
        ),
        migrations.AlterField(
            model_name='attendancedetails',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo'),
        ),
    ]
